### ISSUE TITLE
Readme seems incorrect

### ISSUE THREAD

**Issue by bdutta** [xaizek/vimdoc2html#1]
The Readme.md talks of `vimh2h.py` where-as there is no python script by that name. There is however a `vimd2h.py` which seems a bit similar, but then it doesn't seem to be something that should be invoked directly. Instead, I believe that the script to invoke if `vimdoc2html.py` which is not mentioned in the Readme.md. 
More importantly, python2.x is no longer available (by default) on most systems, and if installed anyhow will lead to a dependency bloat. Therefore, it'd be nice to convert scrips to python3. I've attempted using 2to3 tpython2 to python3 conversion tool.
Having attempted to use the tool, but some problem or other keep popping, latest being:
```Processing /home/falcon74/.vim/pack/plugins/start/vim-go/doc                                                      
Traceback (most recent call last):
  File "/home/falcon74/Work/vimdoc2html-master/vimdoc2html.py", line 66, in <module>
    with file(path.join(src_dir, 'tags'), 'r') as tags_file:
NameError: name 'file' is not defined
```

**Comment by xaizek** [comment]
Thanks. Should be fixed now.
