### ISSUE TITLE
Fails to recognize backquoted `... ...` (w/ spaces) (PAT_COMMAND)

### ISSUE THREAD

**Issue by mralusw** [xaizek/vimdoc2html#10]
Since `PAT_COMMAND` uses
```
r'`([^` ]+)`'
```

it fails to recognize backquoted fragments with spaces, which are quite common. This results in ugly backticks in the HTML rendering.

There's also `PAT_GRAPHIC` which recognizes lines ending in space-backtick (though I don't know what that's supposed to mean).

Either we should change `PAT_COMMAND`, or add a new `PAT_BACKQUOTED` rule, to allows spaces inside backquotes. Spaces shouldn't break the regex since `PAT_GRAPHIC`, like `PAT_COMMAND` is also nested in `PAT_TAGWORD`.

**Comment by xaizek** [comment]
I've never noticed that.  I don't think allowing spaces in `PAT_COMMAND` will cause any problems, not sure why it was excluded.
