### ISSUE TITLE
Non-raw (i.e. with HTML template) generation fails with python2

### ISSUE THREAD

**Issue by bdutta** [xaizek/vimdoc2html#2]
Thanks author for fixing code & Readme for python3. However, when I tried it on a fresh Ubuntu 20.04 server VM with latest python2.7 and perl, on [vim-go.txt](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt) (vimdoc helpfile from `vim-go` vim plugin for Go programming language) it fails with following error:

```$ vimdoc2html.py vim-go.txt
Processing .
Traceback (most recent call last):
  File "/home/bdutta/vimdoc2html-master/vimdoc2html.py", line 84, in <module>
    html=html));
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 37283: ordinal not in range(128)
```

However, when I run it as `vimdoc2html.py -r vim-go.txt` and then manually wrap the generated <XML> with the HTML template text, I do get a very good and usable HTML file. Not sure however, that after the recent fix, the python2 error remains, I suppose somewhere some string had to be treated as unicode.

**Comment by xaizek** [comment]
Thanks. The error was still there. Works fine for Python2 and Python3 now.

**Comment by xaizek** [comment]
No, wait, I fixed a different issue. This one shows up when using non-Unicode locale.

**Comment by xaizek** [comment]
This time should be fixed for real.
