### ISSUE TITLE
Perhaps Readme.md hasn't been fixed completely

### ISSUE THREAD

**Issue by bdutta** [xaizek/vimdoc2html#3]
Unless I am horribly mistaken, the Readme.md is not fully updated for correct usage. My understanding is that instead of directly invoking `vimd2h.py` one should instead be invoking `
vimdoc2html.py`. My python skills are very rudimentary, but isn't it that `vimd2h.py` is a dependency of `vimdoc2html.py`, with the latter having the main ?

**Comment by xaizek** [comment]
Yes, you're correct, thanks.
