### ISSUE TITLE
use non-default template

### ISSUE THREAD

**Issue by mralusw** [xaizek/vimdoc2html#4]
Currently, `vimhelp.css` is included verbatim in the generated HTML file, *or* only an HTML fragment is generated.

`vimhelp.css` seems a bit problematic to include verbatim, in particular since it refers to a dead URL. I've tracked the upstream commit in https://github.com/c4rlo/vimhelp from which it was copied into `vimdoc2html` &mdash; which is still problematic, as there is no license in that version of the repository.

OTOH, generating only a HTML fragment is somewhat inconvenient for the user.

I'm going to add a PR for an optional `--template` argument, to be used instead of the default `TEMPLATE` variable in `vimdoc2html.py`. That way users can add their own styling, CSS href links, headers, footers and whatnot.

**Comment by xaizek** [comment]
I don't expect any licensing issues, the file remained the same after the license was added.  Although maybe the license should be named explicitly.

**Comment by mralusw** [comment]
Yes, the LICENSE should probably be included in the CSS file. And therein lies the dilemma &mdash; I don't know if users (well, me) are so keen on adding a **separate license** (and also a new author) to a project for just a single auto-generated file (either the HTML with inline CSS, or `vimhelp.css`). As things stand *just giving credit in a README* might not be sufficient.

Of course, it's possible to host the CSS / HTML separately (e.g. on GitHub Pages), or one could even drop the CSS completely &mdash; the rendering is good enough even without it.

**Comment by xaizek** [comment]
Well, maybe something like this is enough:
```
SPDX-License-Identifier: MIT
Copyright (c) 2016 Carlo Teubner
```
I know the license says that it needs to be included, but its text is well known.  Can include https://spdx.org/licenses/MIT.html link as well.

**Comment by mralusw** [comment]
Sure, I didn't mean to include the whole text. Just the fact that you get a separately-licensed file (MIT in, say, a GPLv2 or Vim project) seems a bit off-putting. It's one thing to add credits, it's another thing to complicate the licensing for an entire project due to a CSS file...

**Comment by xaizek** [comment]
Writing the CSS anew with a copyright waiver could be a better option.  It's not like the colors are original.  It's Vim's `default` color scheme, maybe slightly adjusted.

**Comment by mralusw** [comment]
Yup, that's what I was thinking. I personally also don't think much of overriding browser behavior (disabling underlining, or visited link coloring etc).

BTW, here's what I've [rendered](https://kstr0k.github.io/vim-visualMarks/vimhelp/visualMarks.txt.html) for a [plugin](https://github.com/kstr0k/vim-visualMarks) I'm working on ([CSS](https://kstr0k.github.io/vim-visualMarks/vimhelp/vimdoc2html.css)). I have yet to deal with colors because I'm not really sure how to best handle dark / light mode nowadays. At the very least, if one sets foreground colors, then maybe there needs to be a root background.
