### ISSUE TITLE
title (class = 'i')

### ISSUE THREAD

**Issue by mralusw** [xaizek/vimdoc2html#7]
Currently `vimd2h.py`, given its upstream purpose, recognizes as "titles" patterns from vim documentation (see `PAT_TITLE`). For other projects this is useless (or maybe worse).

I think the first line should be recognized as a title if it conforms to `:h help-writing` &mdash; though from what I've seen in the wild few projects actually use a `<TAB>` after the initial tag (I would just check for space followed by descriptive text).

I'll push a PR shortly, though I'm not completely sure how to handle this. Currently I'm wrapping the first line in `<span class="i">...</span>`. Maybe a different class would be better. Or maybe the original `PAT_TITLE` should be completely removed from matching.

**Comment by xaizek** [comment]
> For other projects this is useless (or maybe worse).

Don't see how it could be harmful and it's not completely useless.  Plugins could mention version of Vim that they target in a form that matches `Vim version [0-9.a-z]+` regexp.  They could also refer to Vim's reference (although not necessarily in capitalized form).

`<span>` is probably enough, but if both kinds of "titles" are kept, I'd add a separate class and maybe renamed `PAT_TITLE` to `PAT_VIM` or something similar.

**Comment by mralusw** [comment]
Exactly. The original approach seems to match fixed strings wherever they occur in the text. Like if the text randomly mentions some historical fact about Vim version 4, it might generate a "title" span there.

For the actual first line title, I want to mimic `H1` (in the example I gave in #4 I'm using `display: block` and large text). That should definitely not happen for random mentions of Vim versions.

So, yes, if kept, renaming `PAT_TITLE` to `PAT_VIM` would make more sense.

**Comment by mralusw** [comment]
OK, new version in #8, though it looks like I used `PAT_VIM_REF`, not `PAT_VIM`. Either seems to make sense.
